# Generated by Django 6.0.7 on 2026-07-24 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_journalcategory_journalarticlepage_journalarticletag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalarticlepage',
            name='categories',
        ),
        migrations.AddField(
            model_name='journalarticlepage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.journalcategory', verbose_name='選擇所屬六誌 (下拉選單)'),
        ),
    ]
